### ISSUE TITLE
Install error...

### ISSUE THREAD

**Issue by theboyk** [pflouret/overdrive-m4b#1]
I've tried to install this on both macOS 10.14 and 10.13 and when I run the brew install overdrive-m4b command, I get the following error (full output below). Any idea what's wrong?
Thanks!
k.

--- OUTPUT BELOW ---

==> Installing overdrive-m4b from pflouret/tap
==> Downloading https://github.com/pflouret/overdrive-m4b/archive/1.0.0.tar.gz
Already downloaded: /Users/xxxxx/Library/Caches/Homebrew/downloads/6680b7df806ed85b873fd86c2540143944c8206b808274dc069edde6c6d5a521--overdrive-m4b-1.0.0.tar.gz
==> Downloading https://rubygems.org/downloads/nokogiri-1.10.7.gem
Already downloaded: /Users/xxxxx/Library/Caches/Homebrew/downloads/15419440aa22fe1c71c291acda7f95ed3ced8c75784ac571e05c947306eee630--nokogiri-1.10.7.gem
==> gem install /Users/xxxxx/Library/Caches/Homebrew/downloads/15419440aa22fe1c71c291acda7f95ed3ced8c75784ac571e05c947306eee630--nokogiri-1.10.7.gem --ignore-dependencies --no-document --install-dir /usr/local/Cellar/overdrive-m4b/1.0.0/libexec
Last 15 lines from /Users/xxxxx/Library/Logs/Homebrew/overdrive-m4b/01.gem:
	--use-system-libraries
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/dependency.rb:319:in `to_specs': Could not find 'mini_portile2' (~> 2.4.0) among 15 total gem(s) (Gem::LoadError)
Checked in 'GEM_PATH=/private/tmp/overdrive-m4b-20200115-86386-15oj92u/overdrive-m4b-1.0.0/.brew_home/.gem/ruby/2.3.0:/Library/Ruby/Gems/2.3.0:/usr/local/Cellar/overdrive-m4b/1.0.0/libexec:/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/gems/2.3.0', execute `gem env` for more information
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/dependency.rb:328:in `to_spec'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_gem.rb:65:in `gem'
	from extconf.rb:469:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /usr/local/Cellar/overdrive-m4b/1.0.0/libexec/extensions/universal-darwin-18/2.3.0/nokogiri-1.10.7/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /usr/local/Cellar/overdrive-m4b/1.0.0/libexec/gems/nokogiri-1.10.7 for inspection.
Results logged to /usr/local/Cellar/overdrive-m4b/1.0.0/libexec/extensions/universal-darwin-18/2.3.0/nokogiri-1.10.7/gem_make.out

**Comment by andyj682** [comment]
@theboyk Same issue on Ubuntu--did you ever get it working?

**Comment by zanymuzik** [comment]
Were you able to get this to work without libfdk-aac support?

I has similar issues on ubuntu to get this to work directly.
However, I was able to break this in two steps and get it to work.
1. brew install overdrive-m4b --without-fdk-aac
2. For ffmpeg binary with libfdk-aac support - brew install homebrew-ffmpeg/ffmpeg/ffmpeg --with-fdk-aac 

Now, overdrive-m4b runs with the libfdk support because it uses the new binary.

**Comment by Diegus83** [comment]
My installation is failing with the same dependency:

==> Downloading https://rubygems.org/downloads/nokogiri-1.10.7.gem
Already downloaded: /Users/diego/Library/Caches/Homebrew/downloads/15419440aa22fe1c71c291acda7f95ed3ced8c75784ac571e05c947306eee630--nokogiri-1.10.7.gem
==> gem install /Users/diego/Library/Caches/Homebrew/downloads/15419440aa22fe1c71c291acda7f95ed3ced8c75784ac571e05c947306eee630--nokogiri-1.10.7.gem --ignore-dependencies --no-document -
Last 15 lines from /Users/diego/Library/Logs/Homebrew/overdrive-m4b/01.gem:
	--use-system-libraries
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/dependency.rb:319:in `to_specs': Could not find 'mini_portile2' (~> 2.4.0) among 15 total gem(s) (Gem::LoadError)
Checked in 'GEM_PATH=/private/tmp/overdrive-m4b-20201011-70295-oqqr9h/overdrive-m4b-1.0.0/.brew_home/.gem/ruby/2.3.0:/Library/Ruby/Gems/2.3.0:/usr/local/Cellar/overdrive-m4b/1.0.0/libexec:/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/gems/2.3.0', execute `gem env` for more information
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/dependency.rb:328:in `to_spec'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_gem.rb:65:in `gem'
	from extconf.rb:469:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /usr/local/Cellar/overdrive-m4b/1.0.0/libexec/extensions/universal-darwin-17/2.3.0/nokogiri-1.10.7/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /usr/local/Cellar/overdrive-m4b/1.0.0/libexec/gems/nokogiri-1.10.7 for inspection.
Results logged to /usr/local/Cellar/overdrive-m4b/1.0.0/libexec/extensions/universal-darwin-17/2.3.0/nokogiri-1.10.7/gem_make.out

Maybe the brew formula needs to be updated.

Edit: I managed to do some progress. I installed ruby using brew and edited the PATH as recommended so the brew binary for gem will be first. Then I manually installed the dependencies (ffmpeg was already installed on my system). Then I cloned the repository and run the script from the bin directory. Make sure you are using the brew version of ruby and not the one preinstalled with macOS.

**Comment by wista42** [comment]
I am also having this same issue. Not familiar with ruby at all but would be willing try that fix if you could provide steps?

**Comment by Diegus83** [comment]
I have since moved away from the tool and began using odmpy but I will tell you what I remember or can infer from my previous post.

Assuming you are in macOS:
- Install ruby using brew
- Install ffmpeg using brew
- Make sure brew's version of ruby comes first in your path, brew gives you the command to accomplish that upon installation
- Then install the dependencies with `gem install nokogiri` and `gem install id3tag`
- Finally download or clone the repository, cd to overdrive-m4b/bin and run the script

Hope that helps. Good luck!
